# Generated by Django 5.1.6 on 2025-02-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Auditor', 'Auditor'), ('P.R.O', 'P.R.O'), ('Member', 'Member')], default='Member', max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('membership_status', models.BooleanField(default=False)),
                ('membership_type', models.CharField(blank=True, choices=[('Member', 'Member'), ('Worker', 'Worker'), ('Leader', 'Leader')], default='Member', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
