# Generated by Django 5.1.6 on 2025-02-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
