# Generated by Django 5.1.6 on 2025-03-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gallery_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='cover_p',
            field=models.ImageField(blank=True, default='images/profile.jpg', null=True, upload_to='testimony_covers/'),
        ),
    ]
