# Generated by Django 5.1.6 on 2025-04-18 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_testimony_cover_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='testimony',
            name='full_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='testimony',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
